site_name: Desarrollo Web

theme:
  name: material
#  highlightjs: true

nav:
  - Introduccion: introduccion.md
  - Proyecto: proyecto.md
  - Bundling:
    - Webpack: webpack.md
    - MÃ­nimo: webpack_minimo.md
    - Minimizer: webpack_minimizer.md
    - HTML: webpack_html.md
    - React: webpack_react.md
    - Elm: webpack_elm.md
  - Vue:
    - Vue Intro: vue_intro.md
  - Aplicaciones:
    - Escritorio: escritorio.md
  - Libraries:
    - Editores de texto: editores_texto.md
  - PWA:
    - Vue: pwa_vue.md
  - UI Components:
    - Intro: ui_intro.md

markdown_extensions:
- admonition
- codehilite
- pymdownx.details
- pymdownx.superfences

plugins:
- search
