site_name: Desarrollo Web

theme:
  name: mkdocs
  highlightjs: true

nav:
  Introduccion: introduccion.md
  Webpack:
    React: webpack.md
    Elm: webpack_elm.md

markdown_extensions:
- admonition

plugins:
- search
