site_name: Desarrollo Web

theme:
- name: mkdocs
- highlightjs: true

nav:
- 'Introducci√≥n': 'introduccion.md'
- 'Webpack':
  - 'React': 'webpack.md'
  - 'Elm': 'webpack_elm.md'

markdown_extensions:
- toc:
  permalink: "#"

plugins:
- search
